### ISSUE TITLE
Slide for GeometricFlux.jl

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/MeetUpMaterials#14]
Hi @yuehhua,

Could you kindly upload the slide about the GeometricFlux.jl here?

**Comment by yuehhua** [comment]
Here it is.
[slides](https://yuehhua.github.io/slides/geometricflux/)

**Comment by yuehhua** [comment]
Is it better if I provide a pdf file?

**Comment by yuehhua** [comment]
pdf is ready [here](https://github.com/yuehhua/slides/blob/master/geometricflux/geometricflux%20slides.pdf).
