### ISSUE TITLE
Slide for Zygote.jl

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/MeetUpMaterials#15]
Hi @MikeInnes,

Could you kindly upload your slide about Zygote.jl into this repo?

**Comment by MikeInnes** [comment]
Link to google slides is here: https://docs.google.com/presentation/d/1dozjMDv8XKjtm0ANJfqQGSgiyS4HcwQvHk6bWM044Rw/edit#slide=id.g5ba41092a0_1_0

Feel free to download a PDF etc. from there as needed.

**Comment by findmyway** [comment]
Thanks!
